version: '3'

services:
  mysql-docker-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=adminpassword
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports: 
      - 3306:3306
    
  spring-boot-app-container:
    image: spring-boot-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mysql-docker-container
    ports:
      - 8080:8080
    